### ISSUE TITLE
Create css colour classes for every game class

### ISSUE THREAD

**Issue by poppe94** [djaszak/raid_roster_planner#3]

**Comment by djaszak** [comment]
I added the colours in 12265ac7cc3208954c78a20558ad941d86970c35. @poppe94 take a look at the saturation or if we want to alter the colour in another way, then we can close this

**Comment by poppe94** [comment]
There exists a filtering in css see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/saturate) maybe we can use that to apply a saturation value to the background. But im not really sure anymore, if we still need the color when wie have the class icons.

**Comment by djaszak** [comment]
I used the filter.staurate() method to achieve how the colour looks now. I agree with your opinion but I would like to integrate the colour somehow, maybe for the character_name,just so that it fits the design of WoW itself.
