### ISSUE TITLE
Style up splitted tables in character_list.html

### ISSUE THREAD

**Issue by djaszak** [djaszak/raid_roster_planner#4]
At the moment we have 4 basic tables that are splitting up the characters according to their rules. To finish this part of the project for version 1.0 I have some Ideas that should be collected in this issue:

- [x] How do we handle multiple roles? -> mechanism added in a72ea228f3e64401ed9f4e75d7bedffab5afc537

- [x] Overall styling of the containers so that the look of the page is flat like the rest

- [x] Count up the characters in one role

- [x] Add section with non-mains 

- [x] Add some js logic to have the possibility on switching out characters -> see #12 

- [x] Add an overall counter of the characters according to its roles and add a filter for mains/non-mains/all

**Comment by poppe94** [comment]
it would be nice when the 'is main' column is integrated into the character name in my opinion
